from typing import Protocol


class StorageProvider(Protocol):
    async def put(self, key: str, body: bytes, content_type: str) -> str: ...
    async def get(self, key: str) -> bytes: ...
    async def delete(self, key: str) -> None: ...
    async def presign_get(self, key: str, expires_in: int = 3600) -> str: ...
    async def presign_put(self, key: str, content_type: str, expires_in: int = 3600) -> str: ...
