"""add clerk user id

Revision ID: 52f6d0aeed98
Revises: 9b2149fe88da
Create Date: 2026-09-10 14:48:26.413304
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "52f6d0aeed98"
down_revision: str | None = "9b2149fe88da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("clerk_user_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_column("users", "clerk_user_id")
    # ### end Alembic commands ###
