"""initial schema

Revision ID: 9b2149fe88da
Revises: 
Create Date: 2026-09-10 08:40:18.449076
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9b2149fe88da'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('forms',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_forms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms'))
    )
    op.create_index(op.f('ix_forms_owner_id'), 'forms', ['owner_id'], unique=False)
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=True)
    op.create_index(op.f('ix_forms_status'), 'forms', ['status'], unique=False)
    op.create_table('oauth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_identities')),
    sa.UniqueConstraint('provider', 'provider_account_id', name=op.f('uq_oauth_identities_provider'))
    )
    op.create_index(op.f('ix_oauth_identities_user_id'), 'oauth_identities', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_codes'))
    )
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    op.create_table('form_invitations',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_form_invitations_form_id_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_invitations')),
    sa.UniqueConstraint('form_id', 'email', name=op.f('uq_form_invitations_form_id'))
    )
    op.create_index(op.f('ix_form_invitations_form_id'), 'form_invitations', ['form_id'], unique=False)
    op.create_table('form_responses',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('respondent_email', sa.String(length=320), nullable=True),
    sa.Column('respondent_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('primary_input_mode', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_form_responses_form_id_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_responses'))
    )
    op.create_index(op.f('ix_form_responses_form_id'), 'form_responses', ['form_id'], unique=False)
    op.create_index('ix_form_responses_form_status', 'form_responses', ['form_id', 'status'], unique=False)
    op.create_index(op.f('ix_form_responses_respondent_key'), 'form_responses', ['respondent_key'], unique=False)
    op.create_table('form_settings',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('read_questions_aloud', sa.Boolean(), nullable=False),
    sa.Column('autoplay_audio', sa.Boolean(), nullable=False),
    sa.Column('voice_id', sa.String(length=80), nullable=False),
    sa.Column('voice_speed', sa.String(length=10), nullable=False),
    sa.Column('show_live_transcription', sa.Boolean(), nullable=False),
    sa.Column('collect_respondent_email', sa.Boolean(), nullable=False),
    sa.Column('allow_review_and_edit', sa.Boolean(), nullable=False),
    sa.Column('require_sign_in', sa.Boolean(), nullable=False),
    sa.Column('one_response_per_person', sa.Boolean(), nullable=False),
    sa.Column('audience', sa.String(length=30), nullable=False),
    sa.Column('response_limit', sa.Integer(), nullable=True),
    sa.Column('show_progress_bar', sa.Boolean(), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('all_questions_required', sa.Boolean(), nullable=False),
    sa.Column('notify_on_response', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_form_settings_form_id_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_settings'))
    )
    op.create_index(op.f('ix_form_settings_form_id'), 'form_settings', ['form_id'], unique=True)
    op.create_table('form_themes',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('header_font', sa.String(length=60), nullable=False),
    sa.Column('header_size', sa.Integer(), nullable=False),
    sa.Column('question_font', sa.String(length=60), nullable=False),
    sa.Column('question_size', sa.Integer(), nullable=False),
    sa.Column('body_font', sa.String(length=60), nullable=False),
    sa.Column('body_size', sa.Integer(), nullable=False),
    sa.Column('header_image_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_form_themes_form_id_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_themes'))
    )
    op.create_index(op.f('ix_form_themes_form_id'), 'form_themes', ['form_id'], unique=True)
    op.create_table('questions',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tts_audio_key', sa.String(length=512), nullable=True),
    sa.Column('tts_audio_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_questions_form_id_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_form_id'), 'questions', ['form_id'], unique=False)
    op.create_table('answers',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('input_mode', sa.String(length=10), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('selected_option_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('was_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['form_responses.id'], name=op.f('fk_answers_response_id_form_responses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    sa.UniqueConstraint('response_id', 'question_id', name=op.f('uq_answers_response_id'))
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_response_id'), 'answers', ['response_id'], unique=False)
    op.create_table('question_options',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options'))
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('audio_recordings',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('waveform_peaks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_status', sa.String(length=20), nullable=False),
    sa.Column('transcript_confidence', sa.Float(), nullable=True),
    sa.Column('transcript_provider', sa.String(length=40), nullable=True),
    sa.Column('transcript_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_audio_recordings_answer_id_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_recordings'))
    )
    op.create_index(op.f('ix_audio_recordings_answer_id'), 'audio_recordings', ['answer_id'], unique=True)
    op.create_table('file_uploads',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_file_uploads_answer_id_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_uploads'))
    )
    op.create_index(op.f('ix_file_uploads_answer_id'), 'file_uploads', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_answer_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_audio_recordings_answer_id'), table_name='audio_recordings')
    op.drop_table('audio_recordings')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_answers_response_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_form_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_form_themes_form_id'), table_name='form_themes')
    op.drop_table('form_themes')
    op.drop_index(op.f('ix_form_settings_form_id'), table_name='form_settings')
    op.drop_table('form_settings')
    op.drop_index(op.f('ix_form_responses_respondent_key'), table_name='form_responses')
    op.drop_index('ix_form_responses_form_status', table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_form_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_form_invitations_form_id'), table_name='form_invitations')
    op.drop_table('form_invitations')
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_oauth_identities_user_id'), table_name='oauth_identities')
    op.drop_table('oauth_identities')
    op.drop_index(op.f('ix_forms_status'), table_name='forms')
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_index(op.f('ix_forms_owner_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
