/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Up */
        post: operations["sign_up_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log In */
        post: operations["log_in_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/social/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Social Session */
        post: operations["exchange_social_session_v1_auth_social_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Out */
        post: operations["log_out_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_v1_auth_verify_email_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_users_me_patch"];
        trace?: never;
    };
    "/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_v1_users_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Forms */
        get: operations["list_forms_v1_forms_get"];
        put?: never;
        /** Create Form */
        post: operations["create_form_v1_forms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Form */
        get: operations["get_form_v1_forms__form_id__get"];
        put?: never;
        post?: never;
        /** Delete Form */
        delete: operations["delete_form_v1_forms__form_id__delete"];
        options?: never;
        head?: never;
        /** Update Form */
        patch: operations["update_form_v1_forms__form_id__patch"];
        trace?: never;
    };
    "/v1/forms/{form_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Form */
        post: operations["duplicate_form_v1_forms__form_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Form */
        post: operations["publish_form_v1_forms__form_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Responses */
        post: operations["close_responses_v1_forms__form_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Responses */
        post: operations["reopen_responses_v1_forms__form_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_v1_forms__form_id__settings_patch"];
        trace?: never;
    };
    "/v1/forms/{form_id}/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Theme */
        patch: operations["update_theme_v1_forms__form_id__theme_patch"];
        trace?: never;
    };
    "/v1/forms/{form_id}/theme/header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Header Image Url */
        get: operations["header_image_url_v1_forms__form_id__theme_header_get"];
        put?: never;
        /** Upload Header Image */
        post: operations["upload_header_image_v1_forms__form_id__theme_header_post"];
        /** Remove Header Image */
        delete: operations["remove_header_image_v1_forms__form_id__theme_header_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite Respondents */
        post: operations["invite_respondents_v1_forms__form_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Question */
        post: operations["create_question_v1_forms__form_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Question */
        delete: operations["delete_question_v1_forms__form_id__questions__question_id__delete"];
        options?: never;
        head?: never;
        /** Update Question */
        patch: operations["update_question_v1_forms__form_id__questions__question_id__patch"];
        trace?: never;
    };
    "/v1/forms/{form_id}/questions/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Questions */
        post: operations["reorder_questions_v1_forms__form_id__questions_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/questions/dictate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dictate Questions */
        post: operations["dictate_questions_v1_forms__form_id__questions_dictate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/questions/dictate/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dictate Questions From Audio */
        post: operations["dictate_questions_from_audio_v1_forms__form_id__questions_dictate_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Responses */
        get: operations["list_responses_v1_forms__form_id__responses_get"];
        put?: never;
        post?: never;
        /** Delete All Responses */
        delete: operations["delete_all_responses_v1_forms__form_id__responses_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/responses/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Response Overview */
        get: operations["response_overview_v1_forms__form_id__responses_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/responses/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_v1_forms__form_id__responses_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/{form_id}/responses/{response_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Response */
        get: operations["get_response_v1_forms__form_id__responses__response_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/forms/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Form */
        get: operations["get_public_form_v1_public_forms__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/forms/{slug}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Response */
        post: operations["start_response_v1_public_forms__slug__responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/forms/{slug}/responses/{response_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Answer */
        put: operations["save_answer_v1_public_forms__slug__responses__response_id__answers_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/forms/{slug}/responses/{response_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Response */
        post: operations["submit_response_v1_public_forms__slug__responses__response_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/forms/{slug}/questions/{question_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Question Audio */
        get: operations["question_audio_v1_public_forms__slug__questions__question_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/forms/{slug}/responses/{response_id}/answers/{question_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Voice Answer */
        post: operations["submit_voice_answer_v1_public_forms__slug__responses__response_id__answers__question_id__audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voices */
        get: operations["list_voices_v1_speech_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerPublic */
        AnswerPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            input_mode: components["schemas"]["InputMode"];
            /** Text Value */
            text_value: string | null;
            /** Selected Option Ids */
            selected_option_ids: string[];
            /** Value */
            value: {
                [key: string]: unknown;
            };
            /** Was Edited */
            was_edited: boolean;
            recording: components["schemas"]["RecordingPublic"] | null;
        };
        /**
         * AudienceType
         * @enum {string}
         */
        AudienceType: "anyone_with_link" | "invited_only";
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["UserPublic"];
            tokens: components["schemas"]["TokenPair"];
        };
        /** Body_dictate_questions_from_audio_v1_forms__form_id__questions_dictate_audio_post */
        Body_dictate_questions_from_audio_v1_forms__form_id__questions_dictate_audio_post: {
            /** Audio */
            audio: string;
        };
        /** Body_submit_voice_answer_v1_public_forms__slug__responses__response_id__answers__question_id__audio_post */
        Body_submit_voice_answer_v1_public_forms__slug__responses__response_id__answers__question_id__audio_post: {
            /** Audio */
            audio: string;
        };
        /** Body_upload_header_image_v1_forms__form_id__theme_header_post */
        Body_upload_header_image_v1_forms__form_id__theme_header_post: {
            /** Image */
            image: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Password */
            password: string;
            /** Current Password */
            current_password: string;
        };
        /** CloseResponsesRequest */
        CloseResponsesRequest: {
            /** Closing Message */
            closing_message?: string | null;
        };
        /** CreateFormRequest */
        CreateFormRequest: {
            /**
             * Title
             * @default Untitled form
             */
            title: string;
            /** Description */
            description?: string | null;
            /** Template */
            template?: string | null;
        };
        /** CreateQuestionRequest */
        CreateQuestionRequest: {
            type: components["schemas"]["QuestionType"];
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /** Help Text */
            help_text?: string | null;
            /**
             * Is Required
             * @default false
             */
            is_required: boolean;
            /** Position */
            position?: number | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Options */
            options?: components["schemas"]["QuestionOptionInput"][];
        };
        /** DictateQuestionsRequest */
        DictateQuestionsRequest: {
            /** Transcript */
            transcript: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** FormDetail */
        FormDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Slug */
            slug: string;
            status: components["schemas"]["FormStatus"];
            /** Published At */
            published_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Closing Message */
            closing_message: string | null;
            /** Questions */
            questions: components["schemas"]["QuestionPublic"][];
            settings: components["schemas"]["FormSettingsPublic"];
            theme: components["schemas"]["FormThemePublic"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FormSettingsPublic */
        FormSettingsPublic: {
            /** Read Questions Aloud */
            read_questions_aloud: boolean;
            /** Autoplay Audio */
            autoplay_audio: boolean;
            /** Voice Id */
            voice_id: string;
            voice_speed: components["schemas"]["VoiceSpeed"];
            /** Show Live Transcription */
            show_live_transcription: boolean;
            /** Collect Respondent Email */
            collect_respondent_email: boolean;
            /** Allow Review And Edit */
            allow_review_and_edit: boolean;
            /** Require Sign In */
            require_sign_in: boolean;
            /** One Response Per Person */
            one_response_per_person: boolean;
            audience: components["schemas"]["AudienceType"];
            /** Response Limit */
            response_limit: number | null;
            /** Show Progress Bar */
            show_progress_bar: boolean;
            /** Shuffle Questions */
            shuffle_questions: boolean;
            /** All Questions Required */
            all_questions_required: boolean;
            /** Notify On Response */
            notify_on_response: boolean;
        };
        /** FormSettingsUpdate */
        FormSettingsUpdate: {
            /** Read Questions Aloud */
            read_questions_aloud?: boolean | null;
            /** Autoplay Audio */
            autoplay_audio?: boolean | null;
            /** Voice Id */
            voice_id?: string | null;
            voice_speed?: components["schemas"]["VoiceSpeed"] | null;
            /** Show Live Transcription */
            show_live_transcription?: boolean | null;
            /** Collect Respondent Email */
            collect_respondent_email?: boolean | null;
            /** Allow Review And Edit */
            allow_review_and_edit?: boolean | null;
            /** Require Sign In */
            require_sign_in?: boolean | null;
            /** One Response Per Person */
            one_response_per_person?: boolean | null;
            audience?: components["schemas"]["AudienceType"] | null;
            /** Response Limit */
            response_limit?: number | null;
            /** Show Progress Bar */
            show_progress_bar?: boolean | null;
            /** Shuffle Questions */
            shuffle_questions?: boolean | null;
            /** All Questions Required */
            all_questions_required?: boolean | null;
            /** Notify On Response */
            notify_on_response?: boolean | null;
        };
        /**
         * FormStatus
         * @enum {string}
         */
        FormStatus: "draft" | "live" | "closed";
        /** FormSummary */
        FormSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            status: components["schemas"]["FormStatus"];
            /** Response Count */
            response_count: number;
            /** Question Count */
            question_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FormThemePublic */
        FormThemePublic: {
            /** Primary Color */
            primary_color: string;
            /** Header Font */
            header_font: string;
            /** Header Size */
            header_size: number;
            /** Question Font */
            question_font: string;
            /** Question Size */
            question_size: number;
            /** Body Font */
            body_font: string;
            /** Body Size */
            body_size: number;
            /** Header Image Key */
            header_image_key: string | null;
        };
        /** FormThemeUpdate */
        FormThemeUpdate: {
            /** Primary Color */
            primary_color?: string | null;
            /** Header Font */
            header_font?: string | null;
            /** Header Size */
            header_size?: number | null;
            /** Question Font */
            question_font?: string | null;
            /** Question Size */
            question_size?: number | null;
            /** Body Font */
            body_font?: string | null;
            /** Body Size */
            body_size?: number | null;
            /** Header Image Key */
            header_image_key?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InputMode
         * @enum {string}
         */
        InputMode: "voice" | "text";
        /** InviteRequest */
        InviteRequest: {
            /** Emails */
            emails: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /** OptionBreakdown */
        OptionBreakdown: {
            /** Option Id */
            option_id: string | null;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Percentage */
            percentage: number;
        };
        /** PublicForm */
        PublicForm: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["FormStatus"];
            /** Closing Message */
            closing_message: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Questions */
            questions: components["schemas"]["PublicQuestion"][];
            settings: components["schemas"]["PublicFormSettings"];
            theme: components["schemas"]["PublicFormTheme"];
        };
        /** PublicFormSettings */
        PublicFormSettings: {
            /** Read Questions Aloud */
            read_questions_aloud: boolean;
            /** Autoplay Audio */
            autoplay_audio: boolean;
            /** Show Live Transcription */
            show_live_transcription: boolean;
            /** Allow Review And Edit */
            allow_review_and_edit: boolean;
            /** Collect Respondent Email */
            collect_respondent_email: boolean;
            /** Show Progress Bar */
            show_progress_bar: boolean;
            /** All Questions Required */
            all_questions_required: boolean;
        };
        /** PublicFormTheme */
        PublicFormTheme: {
            /** Primary Color */
            primary_color: string;
        };
        /** PublicQuestion */
        PublicQuestion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["QuestionType"];
            /** Prompt */
            prompt: string;
            /** Help Text */
            help_text: string | null;
            /** Position */
            position: number;
            /** Is Required */
            is_required: boolean;
            /** Options */
            options: components["schemas"]["PublicQuestionOption"][];
        };
        /** PublicQuestionOption */
        PublicQuestionOption: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
        };
        /** PublishFormRequest */
        PublishFormRequest: {
            /** @default anyone_with_link */
            audience: components["schemas"]["AudienceType"];
            /**
             * Read Questions Aloud
             * @default true
             */
            read_questions_aloud: boolean;
            /**
             * Show Live Transcription
             * @default true
             */
            show_live_transcription: boolean;
            /**
             * Allow Review And Edit
             * @default true
             */
            allow_review_and_edit: boolean;
        };
        /** PublishedFormResponse */
        PublishedFormResponse: {
            form: components["schemas"]["FormDetail"];
            /** Respondent Url */
            respondent_url: string;
        };
        /** QuestionAudio */
        QuestionAudio: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Audio Url */
            audio_url: string;
        };
        /** QuestionOptionInput */
        QuestionOptionInput: {
            /** Id */
            id?: string | null;
            /** Label */
            label: string;
        };
        /** QuestionOptionPublic */
        QuestionOptionPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Position */
            position: number;
        };
        /** QuestionPublic */
        QuestionPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["QuestionType"];
            /** Prompt */
            prompt: string;
            /** Help Text */
            help_text: string | null;
            /** Position */
            position: number;
            /** Is Required */
            is_required: boolean;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Options */
            options: components["schemas"]["QuestionOptionPublic"][];
        };
        /** QuestionSummary */
        QuestionSummary: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Prompt */
            prompt: string;
            type: components["schemas"]["QuestionType"];
            /** Response Count */
            response_count: number;
            /** Breakdown */
            breakdown: components["schemas"]["OptionBreakdown"][];
            /** Text Answers */
            text_answers: string[];
            /** Average Rating */
            average_rating: number | null;
        };
        /**
         * QuestionType
         * @enum {string}
         */
        QuestionType: "short_answer" | "paragraph" | "multiple_choice" | "checkboxes" | "dropdown" | "date" | "rating" | "file_upload";
        /** RecordingPublic */
        RecordingPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Audio Url */
            audio_url?: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Waveform Peaks */
            waveform_peaks: number[];
            /** Transcript */
            transcript: string | null;
            transcript_status: components["schemas"]["TranscriptStatus"];
            /** Transcript Confidence */
            transcript_confidence: number | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReorderQuestionsRequest */
        ReorderQuestionsRequest: {
            /** Question Ids */
            question_ids: string[];
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** ResponseDetail */
        ResponseDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index */
            index: number;
            /** Total */
            total: number;
            /** Respondent Email */
            respondent_email: string | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            primary_input_mode: components["schemas"]["InputMode"] | null;
            /** Answers */
            answers: components["schemas"]["AnswerPublic"][];
        };
        /** ResponseOverview */
        ResponseOverview: {
            /**
             * Form Id
             * Format: uuid
             */
            form_id: string;
            /** Total Responses */
            total_responses: number;
            /** Completion Rate */
            completion_rate: number;
            /** Average Duration Seconds */
            average_duration_seconds: number | null;
            /** Summaries */
            summaries: components["schemas"]["QuestionSummary"][];
        };
        /** ResponseSession */
        ResponseSession: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Form Id
             * Format: uuid
             */
            form_id: string;
            status: components["schemas"]["ResponseStatus"];
            /** Answers */
            answers: components["schemas"]["AnswerPublic"][];
        };
        /**
         * ResponseStatus
         * @enum {string}
         */
        ResponseStatus: "in_progress" | "submitted" | "abandoned";
        /** SignUpRequest */
        SignUpRequest: {
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Accepted Terms
             * @default false
             */
            accepted_terms: boolean;
        };
        /** SocialExchangeRequest */
        SocialExchangeRequest: {
            /** Token */
            token: string;
        };
        /** StartResponseRequest */
        StartResponseRequest: {
            /** Respondent Email */
            respondent_email?: string | null;
            /** Respondent Key */
            respondent_key?: string | null;
            /** Invitation Token */
            invitation_token?: string | null;
        };
        /** SubmitAnswerRequest */
        SubmitAnswerRequest: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** @default text */
            input_mode: components["schemas"]["InputMode"];
            /** Text Value */
            text_value?: string | null;
            /** Selected Option Ids */
            selected_option_ids?: string[];
            /** Value */
            value?: {
                [key: string]: unknown;
            };
            /**
             * Was Edited
             * @default false
             */
            was_edited: boolean;
        };
        /** SubmitFormRequest */
        SubmitFormRequest: {
            /** Duration Seconds */
            duration_seconds?: number | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * TranscriptStatus
         * @enum {string}
         */
        TranscriptStatus: "pending" | "processing" | "completed" | "failed" | "not_recognised";
        /** UpdateFormRequest */
        UpdateFormRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** UpdateQuestionRequest */
        UpdateQuestionRequest: {
            type?: components["schemas"]["QuestionType"] | null;
            /** Prompt */
            prompt?: string | null;
            /** Help Text */
            help_text?: string | null;
            /** Is Required */
            is_required?: boolean | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Options */
            options?: components["schemas"]["QuestionOptionInput"][] | null;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Email Verified At */
            email_verified_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Code */
            code: string;
        };
        /** VoiceAnswerResult */
        VoiceAnswerResult: {
            /**
             * Answer Id
             * Format: uuid
             */
            answer_id: string;
            status: components["schemas"]["TranscriptStatus"];
            /** Transcript */
            transcript: string | null;
            /** Confidence */
            confidence: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Recognised */
            recognised: boolean;
            /** Selected Option Ids */
            selected_option_ids?: string[];
            /** Rating */
            rating?: number | null;
            /**
             * Needs Confirmation
             * @default false
             */
            needs_confirmation: boolean;
        };
        /** VoicePublic */
        VoicePublic: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Preview Url */
            preview_url: string | null;
        };
        /**
         * VoiceSpeed
         * @enum {string}
         */
        VoiceSpeed: "slow" | "normal" | "fast";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sign_up_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_in_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_social_session_v1_auth_social_clerk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_out_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_email_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_v1_auth_verify_email_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    forgot_password_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    update_me_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_v1_users_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_forms_v1_forms_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: components["schemas"]["FormStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_form_v1_forms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFormRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_form_v1_forms__form_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_form_v1_forms__form_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_form_v1_forms__form_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFormRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_form_v1_forms__form_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_form_v1_forms__form_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishFormRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedFormResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_responses_v1_forms__form_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseResponsesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_responses_v1_forms__form_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_v1_forms__form_id__settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormSettingsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_theme_v1_forms__form_id__theme_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormThemeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormThemePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    header_image_url_v1_forms__form_id__theme_header_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_header_image_v1_forms__form_id__theme_header_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_header_image_v1_forms__form_id__theme_header_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormThemePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_header_image_v1_forms__form_id__theme_header_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormThemePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_respondents_v1_forms__form_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_v1_forms__form_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_v1_forms__form_id__questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_question_v1_forms__form_id__questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_questions_v1_forms__form_id__questions_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderQuestionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dictate_questions_v1_forms__form_id__questions_dictate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictateQuestionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dictate_questions_from_audio_v1_forms__form_id__questions_dictate_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_dictate_questions_from_audio_v1_forms__form_id__questions_dictate_audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_responses_v1_forms__form_id__responses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_responses_v1_forms__form_id__responses_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_overview_v1_forms__form_id__responses_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_v1_forms__form_id__responses_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_response_v1_forms__form_id__responses__response_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                response_id: string;
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_form_v1_public_forms__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicForm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_response_v1_public_forms__slug__responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartResponseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_answer_v1_public_forms__slug__responses__response_id__answers_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                response_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_response_v1_public_forms__slug__responses__response_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                response_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitFormRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    question_audio_v1_public_forms__slug__questions__question_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionAudio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_voice_answer_v1_public_forms__slug__responses__response_id__answers__question_id__audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                response_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_voice_answer_v1_public_forms__slug__responses__response_id__answers__question_id__audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceAnswerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_v1_speech_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePublic"][];
                };
            };
        };
    };
}
